[package]
name = "kvm"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
libc = ">=0.2.39"

kvm-bindings = { path = "../../kvm-bindings" }
sys_util = { path = "../sys_util" }
fc_util = { path = "../fc_util" }

[dev-dependencies]
byteorder = ">=1.2.1"
